from django.contrib import admin
from django.contrib.auth import views as auth
from django.templatetags.static import static
from django.urls import path
from django.views.generic import RedirectView

from compta import views, vues_base, vues_justificatifs, vues_parametres, vues_corrections, vues_journaux, vues_etats, vues_tiers, vues_utilisateurs, vues_rapprochement as rap
from compta import vues_analytique, vues_demarrage, vues_documentation, vues_echanges, vues_licence, vues_plan, vues_referentiels, vues_situation

admin.site.site_header = "ComptaJLC – administration"
admin.site.site_title = "ComptaJLC"

urlpatterns = [
    path("", views.tableau_de_bord, name="tableau_de_bord"),
    path("demarrage/", vues_demarrage.assistant, name="demarrage"),
    path("demarrage/compte/", vues_demarrage.compte, name="demarrage_compte"),
    path("licence/", vues_licence.licence, name="licence"),
    path("situation/", vues_situation.situation, name="situation"),
    path("situation/excel/", vues_situation.situation_excel, name="situation_excel"),
    path("ecritures/", views.ecritures, name="ecritures"),
    path("mouvement/<int:numero>/justificatifs/", vues_justificatifs.ajouter, name="justificatif_ajouter"),
    path("justificatif/<int:pk>/", vues_justificatifs.voir, name="justificatif"),
    path("justificatifs/tout.zip", vues_justificatifs.tout_telecharger, name="justificatifs_tout"),
    path("justificatifs/liens.csv", vues_justificatifs.liens_csv, name="justificatifs_liens_csv"),
    path("justificatifs/a-classer/", vues_justificatifs.a_classer, name="justificatifs_a_classer"),
    path("justificatifs/a-classer/voir/", vues_justificatifs.voir_a_classer, name="justificatif_a_classer_voir"),
    path("justificatif/<int:pk>/supprimer/", vues_justificatifs.supprimer, name="justificatif_supprimer"),
    path("justificatif/<int:pk>/copier/", vues_justificatifs.copier, name="justificatif_copier"),
    path("mouvement/<int:numero>/", views.mouvement, name="mouvement"),
    path("mouvement/<int:numero>/modifier/", vues_corrections.modifier, name="mouvement_modifier"),
    path("mouvement/<int:numero>/supprimer/", vues_corrections.supprimer, name="mouvement_supprimer"),
    path("mouvement/rappel/", vues_corrections.rappeler, name="mouvement_rappel"),
    path("mouvement/nouveau/", vues_corrections.nouveau, name="mouvement_nouveau"),
    path("grand-livre/", views.grand_livre, name="grand_livre"),
    path("axes/", vues_analytique.axes_comptes, name="axes_comptes"),
    path("balance/", views.balance, name="balance"),
    path("analytique/", vues_analytique.analytique, name="analytique"),
    path("analytique/detail/", vues_analytique.analytique_detail, name="analytique_detail"),
    path("controles/", views.controles, name="controles"),
    path("modifications/", views.modifications, name="modifications"),
    path("modifications/excel/", vues_journaux.historique_excel, name="historique_excel"),
    path("modifications/effacer/", vues_journaux.effacer_historique, name="effacer_historique"),
    path("journaux/", vues_journaux.journaux, name="journaux"),
    path("saisie/", views.saisie, name="saisie"),
    path("codes/", views.codes, name="codes"),
    path("rapprochement/", rap.accueil, name="rapprochement"),
    path("rapprochement/traductions/", rap.traductions, name="traductions"),
    path("rapprochement/historique/", rap.historique, name="releves_historique"),
    path("rapprochement/<str:code>/", rap.accueil, name="rapprochement_journal"),
    path("rapprochement/<str:code>/parametres/", rap.parametres, name="releve_parametres"),
    path("rapprochement/<str:code>/import/", rap.importer, name="releve_import"),
    path("tiers/", vues_tiers.liste, name="tiers"),
    path("tiers/modele-tiers.xlsx", vues_tiers.modele_tiers, name="modele_tiers"),
    path("tiers/<str:numero>/", vues_tiers.fiche, name="tiers_fiche"),
    path("etats/", vues_etats.etats_annuels, name="etats"),
    path("etats/export/", vues_etats.export_etats, name="export_etats"),
    path("cloture/", vues_etats.cloture, name="cloture"),
    path("cloture/archive/<int:pk>/", vues_etats.archive, name="archive"),
    path("connexion/", auth.LoginView.as_view(template_name="compta/connexion.html"), name="login"),
    path("deconnexion/", auth.LogoutView.as_view(), name="logout"),
    path("mon-compte/", vues_utilisateurs.mon_compte, name="mon_compte"),
    path("utilisateurs/", vues_utilisateurs.utilisateurs, name="utilisateurs"),
    path("utilisateurs/<int:pk>/", vues_utilisateurs.utilisateur, name="utilisateur"),
    path("echanges/", vues_echanges.echanges, name="echanges"),
    path("echanges/exports/<str:nom>", vues_echanges.telecharger, name="echanges_telecharger"),
    path("echanges/modeles.zip", vues_echanges.modeles, name="echanges_modeles"),
    path("documentation/<str:nom>.pdf", vues_documentation.document, name="document"),
    path("referentiels/", vues_referentiels.liste, name="referentiels"),
    path("referentiels/<str:nom>.xlsx", vues_referentiels.exporter, name="referentiel_export"),
    path("base/", vues_base.base, name="base"),
    path("parametres/", vues_parametres.parametres, name="parametres"),
    path("parametres/Parametres.xlsx", vues_parametres.telecharger, name="parametres_telecharger"),
    path("base/telecharger/", vues_base.telecharger, name="base_telecharger"),
    path("base/telecharger/<str:nom>", vues_base.telecharger, name="base_telecharger_fichier"),
    path("base/archive/<str:nom>", vues_base.telecharger_archive, name="base_archive"),
    path("base/export/<str:nom>", vues_base.telecharger_export, name="base_export"),
    path("plan/", vues_plan.plan, name="plan"),
    path("plan/nouveau/", vues_plan.compte, name="compte_nouveau"),
    path("plan/<str:numero>/", vues_plan.compte, name="compte"),
    path("parametrage/journaux/", vues_plan.journaux_param, name="journaux_param"),
    path("parametrage/journaux/nouveau/", vues_plan.journal, name="journal_nouveau"),
    path("parametrage/journaux/<str:code>/", vues_plan.journal, name="journal"),
    path("parametrage/axes/", vues_plan.axes_param, name="axes_param"),
    path("parametrage/axes/<str:code>/", vues_plan.code_axe, name="code_axe"),
    path("admin/", admin.site.urls),
    path("favicon.ico", RedirectView.as_view(url=static("compta/favicon.ico"), permanent=True)),
]
