# Generated by Django 5.2.17 on 2026-09-26 10:28

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CodeAnalytique",
            fields=[
                (
                    "code",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                (
                    "axe",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Axe 1"), (2, "Axe 2")]
                    ),
                ),
                (
                    "libelle",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="libellé"
                    ),
                ),
                (
                    "statut",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Non affecté"), (1, "En cours"), (2, "Terminé")],
                        default=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "code analytique",
                "verbose_name_plural": "codes analytiques",
                "ordering": ["axe", "code"],
            },
        ),
        migrations.CreateModel(
            name="Exercice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("libelle", models.CharField(max_length=40, verbose_name="libellé")),
                ("debut", models.DateField(verbose_name="début")),
                ("fin", models.DateField()),
                (
                    "clos",
                    models.BooleanField(
                        default=False,
                        help_text="Aucune écriture nouvelle dans un exercice clos (RG-04).",
                    ),
                ),
            ],
            options={
                "ordering": ["debut"],
            },
        ),
        migrations.CreateModel(
            name="Modification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("auteur", models.CharField(max_length=100)),
                ("lot", models.CharField(blank=True, max_length=20)),
                ("action", models.CharField(max_length=40)),
                ("objet", models.CharField(max_length=200)),
                ("avant", models.CharField(blank=True, max_length=300)),
                (
                    "apres",
                    models.CharField(blank=True, max_length=300, verbose_name="après"),
                ),
            ],
            options={
                "verbose_name": "modification",
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Prefixe",
            fields=[
                (
                    "prefixe",
                    models.CharField(
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        verbose_name="préfixe",
                    ),
                ),
                (
                    "axe",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Axe 1"), (2, "Axe 2")]
                    ),
                ),
                (
                    "libelle",
                    models.CharField(blank=True, max_length=60, verbose_name="libellé"),
                ),
            ],
            options={
                "verbose_name": "préfixe",
                "ordering": ["axe", "prefixe"],
            },
        ),
        migrations.CreateModel(
            name="Reglage",
            fields=[
                (
                    "cle",
                    models.CharField(
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                        verbose_name="clé",
                    ),
                ),
                ("valeur", models.CharField(max_length=200)),
                ("description", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "verbose_name": "réglage",
            },
        ),
        migrations.CreateModel(
            name="Compte",
            fields=[
                (
                    "numero",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="compte",
                    ),
                ),
                ("libelle", models.CharField(max_length=100, verbose_name="libellé")),
                ("lettrable", models.BooleanField(default=False)),
                ("actif", models.BooleanField(default=True)),
                (
                    "anal1",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"axe": 1},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comptes",
                        to="compta.codeanalytique",
                        verbose_name="axe 1",
                    ),
                ),
            ],
            options={
                "ordering": ["numero"],
            },
        ),
        migrations.CreateModel(
            name="Journal",
            fields=[
                (
                    "code",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("intitule", models.CharField(max_length=60, verbose_name="intitulé")),
                ("type", models.CharField(blank=True, max_length=10)),
                ("actif", models.BooleanField(default=True)),
                (
                    "compte",
                    models.ForeignKey(
                        blank=True,
                        help_text="Compte de trésorerie des journaux de banque et de caisse.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="compta.compte",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "journaux",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Mouvement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.PositiveIntegerField(unique=True, verbose_name="Mvt"),
                ),
                ("date", models.DateField()),
                ("piece", models.PositiveIntegerField(verbose_name="pièce")),
                (
                    "origine",
                    models.CharField(
                        choices=[
                            ("import", "Reprise"),
                            ("saisie", "Saisie"),
                            ("liaison", "Fiche bénévole"),
                            ("correction", "Correction"),
                        ],
                        default="saisie",
                        max_length=12,
                    ),
                ),
                (
                    "commentaire",
                    models.TextField(
                        blank=True,
                        help_text="Origine et motif d'une écriture ajoutée ou corrigée (RG-05).",
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="compta.journal"
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-numero"],
            },
        ),
        migrations.CreateModel(
            name="Ligne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordre", models.PositiveSmallIntegerField(default=0)),
                ("libelle", models.CharField(max_length=200, verbose_name="libellé")),
                (
                    "debit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="débit",
                    ),
                ),
                (
                    "credit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="crédit",
                    ),
                ),
                ("lettrage", models.CharField(blank=True, max_length=10)),
                (
                    "anal2",
                    models.ForeignKey(
                        limit_choices_to={"axe": 2},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lignes",
                        to="compta.codeanalytique",
                        verbose_name="axe 2",
                    ),
                ),
                (
                    "compte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lignes",
                        to="compta.compte",
                    ),
                ),
                (
                    "mouvement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="compta.mouvement",
                    ),
                ),
            ],
            options={
                "ordering": ["mouvement", "ordre"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("debit__gt", 0), ("credit", 0)),
                            models.Q(("credit__gt", 0), ("debit", 0)),
                            _connector="OR",
                        ),
                        name="debit_ou_credit",
                    )
                ],
            },
        ),
    ]
