# Generated by Django 5.2.17 on 2026-09-26 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compta", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TypeTiers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "libelle",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="libellé"
                    ),
                ),
                (
                    "prefixe",
                    models.CharField(max_length=10, verbose_name="préfixe de compte"),
                ),
            ],
            options={
                "verbose_name": "type de tiers",
                "verbose_name_plural": "types de tiers",
            },
        ),
        migrations.CreateModel(
            name="LigneSchema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("schema", models.CharField(max_length=4, verbose_name="schéma")),
                ("ligne", models.PositiveSmallIntegerField()),
                (
                    "mvt",
                    models.PositiveSmallIntegerField(default=1, verbose_name="Mvt"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("TIERS", "compte du tiers"),
                            ("CONTREPARTIE", "compte du modèle ou saisi"),
                            ("TRESO", "banque ou caisse"),
                            ("DEST", "banque qui reçoit"),
                            ("VIREMENT", "compte de virement interne"),
                        ],
                        max_length=12,
                        verbose_name="rôle",
                    ),
                ),
                (
                    "sens",
                    models.CharField(
                        choices=[("D", "Débit"), ("C", "Crédit")], max_length=1
                    ),
                ),
                (
                    "si_regle",
                    models.BooleanField(
                        default=False, verbose_name="seulement si réglé"
                    ),
                ),
                (
                    "journal",
                    models.CharField(
                        choices=[
                            (
                                "PAIEMENT_OU_DEFAUT",
                                "paiement si réglé, sinon journal du modèle",
                            ),
                            ("DEFAUT", "journal du modèle"),
                            ("PAIEMENT", "journal du paiement"),
                            ("DESTINATION", "journal de la banque qui reçoit"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "ligne de schéma",
                "verbose_name_plural": "schémas d'écritures",
                "ordering": ["schema", "ligne"],
                "unique_together": {("schema", "ligne")},
            },
        ),
        migrations.CreateModel(
            name="MoyenPaiement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "libelle",
                    models.CharField(
                        max_length=40, unique=True, verbose_name="libellé"
                    ),
                ),
                ("ordre", models.PositiveSmallIntegerField(default=0)),
                (
                    "journal",
                    models.ForeignKey(
                        blank=True,
                        help_text="Vide pour « Non réglé » (facture seule).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="compta.journal",
                    ),
                ),
            ],
            options={
                "verbose_name": "moyen de paiement",
                "verbose_name_plural": "moyens de paiement",
                "ordering": ["ordre", "libelle"],
            },
        ),
        migrations.CreateModel(
            name="ModeleOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        max_length=60, unique=True, verbose_name="type d'opération"
                    ),
                ),
                ("schema", models.CharField(max_length=4, verbose_name="schéma")),
                ("paiement_obligatoire", models.BooleanField(default=True)),
                (
                    "classe",
                    models.CharField(
                        blank=True,
                        help_text="Classe attendue du compte (6 ou 7).",
                        max_length=1,
                    ),
                ),
                (
                    "libelle_type",
                    models.CharField(max_length=40, verbose_name="libellé type"),
                ),
                ("aide", models.CharField(blank=True, max_length=200)),
                ("ordre", models.PositiveSmallIntegerField(default=0)),
                ("actif", models.BooleanField(default=True)),
                (
                    "compte",
                    models.ForeignKey(
                        blank=True,
                        help_text="Compte de charge ou de produit proposé ; vide = à choisir à la saisie.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="compta.compte",
                    ),
                ),
                (
                    "journal_defaut",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="compta.journal",
                        verbose_name="journal par défaut",
                    ),
                ),
                (
                    "tiers",
                    models.ForeignKey(
                        blank=True,
                        help_text="Vide = sans tiers.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="compta.typetiers",
                    ),
                ),
            ],
            options={
                "verbose_name": "modèle d'opération",
                "verbose_name_plural": "modèles d'opérations",
                "ordering": ["ordre", "type"],
            },
        ),
    ]
