# Generated by Django 5.2.17 on 2026-09-26 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compta", "0002_typetiers_ligneschema_moyenpaiement_modeleoperation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Fiche",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("activite", "Activité"), ("gestion", "Gestion")],
                        max_length=10,
                    ),
                ),
                ("titre", models.CharField(max_length=100)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("ouverte", "Ouverte : saisie du bénévole"),
                            ("transmise", "Transmise au trésorier"),
                            ("reportee", "Reportée en comptabilité"),
                        ],
                        default="ouverte",
                        max_length=10,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                (
                    "anal2",
                    models.ForeignKey(
                        blank=True,
                        help_text="Activité : fixé d'avance par le trésorier.",
                        limit_choices_to={"axe": 2},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="compta.codeanalytique",
                        verbose_name="code axe 2",
                    ),
                ),
                (
                    "benevoles",
                    models.ManyToManyField(
                        blank=True,
                        related_name="fiches",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="bénévoles",
                    ),
                ),
            ],
            options={
                "ordering": ["-cree_le"],
                "permissions": [
                    ("gerer_fiche", "Compléter et reporter les fiches bénévoles")
                ],
            },
        ),
        migrations.CreateModel(
            name="ModeFiche",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_fiche",
                    models.CharField(
                        choices=[("activite", "Activité"), ("gestion", "Gestion")],
                        max_length=10,
                        verbose_name="fiche",
                    ),
                ),
                (
                    "sens",
                    models.CharField(
                        choices=[("R", "Recette"), ("D", "Dépense"), ("*", "Les deux")],
                        default="*",
                        max_length=1,
                    ),
                ),
                ("libelle", models.CharField(max_length=40, verbose_name="libellé")),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("TRESO", "banque, caisse ou carte"),
                            ("NON_PAYE", "non payé : reste dû par le membre"),
                            ("AVANCE", "avance d'un membre : dette envers lui"),
                        ],
                        default="TRESO",
                        max_length=10,
                    ),
                ),
                ("ordre", models.PositiveSmallIntegerField(default=0)),
                (
                    "compte",
                    models.ForeignKey(
                        blank=True,
                        help_text="Vide sauf pour TRESO.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="compta.compte",
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="compta.journal"
                    ),
                ),
            ],
            options={
                "verbose_name": "mode de paiement (fiche bénévole)",
                "verbose_name_plural": "modes de paiement (fiches bénévoles)",
                "ordering": ["type_fiche", "ordre"],
                "unique_together": {("type_fiche", "sens", "libelle")},
            },
        ),
        migrations.CreateModel(
            name="NatureFiche",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_fiche",
                    models.CharField(
                        choices=[("activite", "Activité"), ("gestion", "Gestion")],
                        max_length=10,
                        verbose_name="fiche",
                    ),
                ),
                (
                    "sens",
                    models.CharField(
                        choices=[("R", "Recette"), ("D", "Dépense")], max_length=1
                    ),
                ),
                ("libelle", models.CharField(max_length=60, verbose_name="libellé")),
                (
                    "libelle_ecriture",
                    models.CharField(max_length=40, verbose_name="libellé d'écriture"),
                ),
                ("ordre", models.PositiveSmallIntegerField(default=0)),
                (
                    "compte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="compta.compte"
                    ),
                ),
            ],
            options={
                "verbose_name": "nature (fiche bénévole)",
                "verbose_name_plural": "natures (fiches bénévoles)",
                "ordering": ["type_fiche", "sens", "ordre"],
                "unique_together": {("type_fiche", "sens", "libelle")},
            },
        ),
        migrations.CreateModel(
            name="TiersProvisoire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=60)),
                (
                    "prenom",
                    models.CharField(blank=True, max_length=60, verbose_name="prénom"),
                ),
                (
                    "remarque",
                    models.CharField(
                        blank=True, help_text="Téléphone, e-mail…", max_length=100
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                (
                    "compte",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="compta.compte",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "tiers provisoire",
                "verbose_name_plural": "tiers provisoires",
                "ordering": ["nom", "prenom"],
            },
        ),
        migrations.CreateModel(
            name="LigneFiche",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sens",
                    models.CharField(
                        choices=[("R", "Recette"), ("D", "Dépense")], max_length=1
                    ),
                ),
                ("date", models.DateField()),
                (
                    "autre",
                    models.CharField(
                        blank=True,
                        max_length=60,
                        verbose_name="autre payeur ou bénéficiaire",
                    ),
                ),
                (
                    "personnes",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="nombre de personnes"
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=12)),
                ("justificatif", models.CharField(blank=True, max_length=60)),
                ("remarque", models.CharField(blank=True, max_length=100)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                (
                    "anal2",
                    models.ForeignKey(
                        blank=True,
                        help_text="Gestion : choisi par le trésorier.",
                        limit_choices_to={"axe": 2},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="compta.codeanalytique",
                        verbose_name="code axe 2",
                    ),
                ),
                (
                    "compte",
                    models.ForeignKey(
                        blank=True,
                        help_text="Vide = compte de la nature.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="compta.compte",
                        verbose_name="compte de contrepartie",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fiche",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="compta.fiche",
                    ),
                ),
                (
                    "mouvement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lignes_fiche",
                        to="compta.mouvement",
                    ),
                ),
                (
                    "tiers",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lignes_fiche",
                        to="compta.compte",
                        verbose_name="membre",
                    ),
                ),
                (
                    "mode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="compta.modefiche",
                        verbose_name="mode de paiement",
                    ),
                ),
                (
                    "nature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="compta.naturefiche",
                    ),
                ),
                (
                    "provisoire",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lignes",
                        to="compta.tiersprovisoire",
                        verbose_name="nouveau tiers",
                    ),
                ),
            ],
            options={
                "verbose_name": "ligne de fiche",
                "verbose_name_plural": "lignes de fiches",
                "ordering": ["date", "id"],
            },
        ),
    ]
