# Generated by Django 5.2.17 on 2026-09-26 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compta", "0003_fiches_benevoles"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ParametreReleve",
            fields=[
                (
                    "journal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="compta.journal",
                    ),
                ),
                (
                    "date_reprise",
                    models.DateField(
                        blank=True,
                        help_text="Les lignes du relevé antérieures sont couvertes par l'à-nouveau.",
                        null=True,
                        verbose_name="date de reprise en compta",
                    ),
                ),
                (
                    "libelle",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="description du relevé"
                    ),
                ),
            ],
            options={
                "verbose_name": "paramètres de relevé",
                "verbose_name_plural": "paramètres de relevés",
            },
        ),
        migrations.CreateModel(
            name="Traduction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cle",
                    models.CharField(
                        help_text="Texte hébreu sans espaces ni parenthèses.",
                        max_length=120,
                        unique=True,
                        verbose_name="clé",
                    ),
                ),
                (
                    "hebreu",
                    models.CharField(max_length=120, verbose_name="opération (hébreu)"),
                ),
                ("traduction", models.CharField(max_length=120)),
            ],
            options={
                "verbose_name": "traduction (relevé)",
                "verbose_name_plural": "traductions (relevés)",
                "ordering": ["traduction"],
            },
        ),
        migrations.CreateModel(
            name="Rapprochement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("auto", "Automatique"),
                            ("manuel", "Manuel"),
                            ("saisie", "Écriture créée"),
                        ],
                        max_length=10,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rapprochements",
                        to="compta.journal",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
                "permissions": [("pointer_releve", "Importer les relevés et pointer")],
            },
        ),
        migrations.AddField(
            model_name="ligne",
            name="rapprochement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ecritures",
                to="compta.rapprochement",
            ),
        ),
        migrations.CreateModel(
            name="LigneReleve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "rang",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="Rang dans la journée (ordre du relevé)."
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="référence"
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="opération (relevé)"
                    ),
                ),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Positif = crédit en banque (entrée).",
                        max_digits=14,
                    ),
                ),
                (
                    "solde",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="solde relevé",
                    ),
                ),
                (
                    "ouverture",
                    models.BooleanField(
                        default=False, verbose_name="solde d'ouverture"
                    ),
                ),
                ("source", models.CharField(blank=True, max_length=120)),
                ("importe_le", models.DateTimeField(auto_now_add=True)),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="releve",
                        to="compta.journal",
                    ),
                ),
                (
                    "rapprochement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="releves",
                        to="compta.rapprochement",
                    ),
                ),
            ],
            options={
                "verbose_name": "ligne de relevé",
                "verbose_name_plural": "lignes de relevés",
                "ordering": ["journal", "date", "rang"],
                "unique_together": {
                    ("journal", "date", "reference", "montant", "rang")
                },
            },
        ),
    ]
