# Generated by Django 5.2.17 on 2026-09-26 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compta", "0004_rapprochement"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercice",
            name="archive",
            field=models.CharField(
                blank=True,
                help_text="Classeur figé en valeurs (dossier data/archives).",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="exercice",
            name="cloture_le",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="clôturé le"
            ),
        ),
        migrations.AddField(
            model_name="exercice",
            name="cloture_par",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="clôturé par"
            ),
        ),
        migrations.AddField(
            model_name="exercice",
            name="mouvement_an",
            field=models.ForeignKey(
                blank=True,
                help_text="Mvt d'à-nouveaux créé par la clôture.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="compta.mouvement",
                verbose_name="à-nouveaux générés",
            ),
        ),
        migrations.AddField(
            model_name="exercice",
            name="resultat",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=14,
                null=True,
                verbose_name="résultat affecté",
            ),
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nature",
                    models.CharField(
                        choices=[("C", "Charges"), ("P", "Produits")], max_length=1
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "anal1",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"axe": 1},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="compta.codeanalytique",
                        verbose_name="axe 1",
                    ),
                ),
                (
                    "anal2",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"axe": 2},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="compta.codeanalytique",
                        verbose_name="axe 2",
                    ),
                ),
                (
                    "compte",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="compta.compte",
                    ),
                ),
                (
                    "exercice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budgets",
                        to="compta.exercice",
                    ),
                ),
            ],
            options={
                "ordering": ["exercice", "nature", "compte", "anal1", "anal2"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("anal1__isnull", True),
                                ("anal2__isnull", True),
                                ("compte__isnull", False),
                            ),
                            models.Q(
                                ("anal1__isnull", False),
                                ("anal2__isnull", True),
                                ("compte__isnull", True),
                            ),
                            models.Q(
                                ("anal1__isnull", True),
                                ("anal2__isnull", False),
                                ("compte__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="budget_une_cible",
                    )
                ],
            },
        ),
    ]
