# Generated by Django 5.2.17 on 2026-09-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compta", "0005_cloture_budget"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mouvement",
            name="origine",
            field=models.CharField(
                choices=[
                    ("import", "Reprise"),
                    ("saisie", "Saisie"),
                    ("liaison", "Fiche bénévole"),
                    ("correction", "Correction"),
                    ("cloture", "À-nouveaux de clôture"),
                ],
                default="saisie",
                max_length=12,
            ),
        ),
    ]
