# Generated by Django 5.2.17 on 2026-09-26 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compta", "0006_origine_cloture"),
    ]

    operations = [
        migrations.CreateModel(
            name="Membre",
            fields=[
                (
                    "compte",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        related_name="membre",
                        serialize=False,
                        to="compta.compte",
                    ),
                ),
                ("nom", models.CharField(max_length=60)),
                (
                    "prenom",
                    models.CharField(blank=True, max_length=60, verbose_name="prénom"),
                ),
                (
                    "telephone",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="téléphone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="e-mail"
                    ),
                ),
                (
                    "date_adhesion",
                    models.DateField(
                        blank=True, null=True, verbose_name="date d'adhésion"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("actif", "Actif"),
                            ("honoraire", "Honoraire"),
                            ("demissionnaire", "Démissionnaire"),
                        ],
                        default="actif",
                        max_length=15,
                    ),
                ),
                (
                    "cotisation",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="cotisation annuelle attendue",
                    ),
                ),
            ],
            options={
                "ordering": ["nom", "prenom"],
            },
        ),
    ]
