# Generated by Django 5.2.17 on 2026-09-26 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compta", "0007_membres"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="membre",
            options={
                "ordering": ["nom", "prenom"],
                "verbose_name": "fiche tiers",
                "verbose_name_plural": "fiches tiers",
            },
        ),
        migrations.AddField(
            model_name="membre",
            name="adresse",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="membre",
            name="code_postal",
            field=models.CharField(
                blank=True, max_length=12, verbose_name="code postal"
            ),
        ),
        migrations.AddField(
            model_name="membre",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="compta.typetiers",
                verbose_name="type de tiers",
            ),
        ),
        migrations.AddField(
            model_name="membre",
            name="ville",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name="membre",
            name="nom",
            field=models.CharField(max_length=60, verbose_name="nom ou raison sociale"),
        ),
    ]
