# Generated by Django 5.2.17 on 2026-09-27 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compta", "0008_tiers_adresse"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reglage",
            options={
                "permissions": [
                    (
                        "echanger_fichiers",
                        "Importer et exporter des fichiers (dossiers Imports et Exports)",
                    )
                ],
                "verbose_name": "réglage",
            },
        ),
        migrations.AlterField(
            model_name="exercice",
            name="archive",
            field=models.CharField(
                blank=True,
                help_text="Classeur figé en valeurs (dossier Exports/Archives).",
                max_length=200,
            ),
        ),
    ]
