# Generated by Django 5.2.17 on 2026-09-27 09:35

from django.db import migrations


def administrateurs(apps, schema_editor):
    """Les comptes « superutilisateur » existants (trésoriers créés avant ce rôle) deviennent administrateurs."""
    Group, User = apps.get_model("auth", "Group"), apps.get_model("auth", "User")
    admin, _ = Group.objects.get_or_create(name="Administrateur")
    tresorier = Group.objects.filter(name="Trésorier").first()
    for u in User.objects.filter(is_superuser=True):
        u.groups.add(admin)
        if tresorier:
            u.groups.remove(tresorier)
        if not u.is_staff:
            u.is_staff = True
            u.save(update_fields=["is_staff"])
    verificateur = Group.objects.filter(name="Vérificateur").first()     # rôle supprimé : ses utilisateurs passent au Bureau
    if verificateur:
        bureau, _ = Group.objects.get_or_create(name="Bureau")
        for u in verificateur.user_set.all():
            u.groups.add(bureau)
        verificateur.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("compta", "0010_benevole_membre"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reglage",
            options={
                "permissions": [
                    (
                        "echanger_fichiers",
                        "Importer et exporter des fichiers (dossiers Imports et Exports)",
                    ),
                    ("parametrer", "Modifier le paramétrage de base (administrateur)"),
                ],
                "verbose_name": "réglage",
            },
        ),
        migrations.RunPython(administrateurs, migrations.RunPython.noop),
    ]
