# Generated by Django 5.2.17 on 2026-09-28 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compta", "0010_justificatifs"),
    ]

    operations = [
        migrations.AddField(
            model_name="justificatif",
            name="lien",
            field=models.URLField(
                blank=True,
                help_text="Document consultable en ligne (SUMIT…).",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="justificatif",
            name="chemin",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
