# Generated by Django 5.2.17 on 2026-09-28 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compta", "0013_fusion_justificatifs"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentFiche",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chemin", models.CharField(max_length=255, unique=True)),
                (
                    "nom",
                    models.CharField(max_length=150, verbose_name="fichier d'origine"),
                ),
                ("description", models.CharField(blank=True, max_length=150)),
                ("taille", models.PositiveIntegerField(default=0)),
                (
                    "ajoute_le",
                    models.DateTimeField(auto_now_add=True, verbose_name="ajouté le"),
                ),
                (
                    "ajoute_par",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ajouté par"
                    ),
                ),
                (
                    "fiche",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="compta.fiche",
                    ),
                ),
                (
                    "ligne",
                    models.ForeignKey(
                        blank=True,
                        help_text="Vide = document de toute la fiche.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="compta.lignefiche",
                    ),
                ),
            ],
            options={
                "ordering": ["fiche", "ajoute_le", "id"],
            },
        ),
    ]
