# Generated by Django 5.2.17 on 2026-09-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compta", "0016_reglages_association"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reglage",
            name="valeur",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
