# Generated by Django 5.2.17 on 2026-09-29 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compta", "0017_reglage_valeur_longue"),
    ]

    operations = [
        migrations.AddField(
            model_name="journal",
            name="devise",
            field=models.CharField(
                blank=True,
                help_text="Devise du compte (ILS, USD…) si ce n'est pas celle de la comptabilité : les écritures gardent aussi leur montant d'origine. Vide = devise de la compta.",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="ligne",
            name="montant_devise",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Journal en devise : montant dans la devise du journal (même sens).",
                max_digits=14,
                null=True,
                verbose_name="montant d'origine",
            ),
        ),
    ]
