# Generated by Django 5.2.17 on 2026-09-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compta", "0018_devise_par_journal"),
    ]

    operations = [
        migrations.CreateModel(
            name="TauxChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jour", models.DateField()),
                ("devise", models.CharField(max_length=3)),
                ("taux", models.DecimalField(decimal_places=6, max_digits=14)),
            ],
            options={
                "verbose_name": "cours de change",
                "verbose_name_plural": "cours de change (BCE)",
                "ordering": ["-jour", "devise"],
                "unique_together": {("jour", "devise")},
            },
        ),
    ]
