# Generated by Django 5.2.17 on 2026-09-29 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compta", "0019_cours_bce"),
    ]

    operations = [
        migrations.CreateModel(
            name="AxeCompte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=40, unique=True)),
                ("ordre", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "axe de comptes",
                "verbose_name_plural": "axes de comptes",
                "ordering": ["ordre", "nom"],
            },
        ),
        migrations.CreateModel(
            name="ValeurCompte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valeur", models.CharField(max_length=100)),
                (
                    "axe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valeurs",
                        to="compta.axecompte",
                    ),
                ),
                (
                    "compte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valeurs_axes",
                        to="compta.compte",
                    ),
                ),
            ],
            options={
                "verbose_name": "valeur d'axe de comptes",
                "verbose_name_plural": "valeurs d'axes de comptes",
                "ordering": ["axe", "compte"],
                "unique_together": {("compte", "axe")},
            },
        ),
    ]
