# Generated by Django 5.2.17 on 2026-10-01 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("compta", "0018_sans_sumit"),
        ("compta", "0020_axes_de_comptes"),
    ]

    operations = []
