# Generated by Django 5.2.17 on 2026-10-02 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compta", "0021_merge_0018_sans_sumit_0020_axes_de_comptes"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TauxChange",
        ),
        migrations.RemoveField(
            model_name="journal",
            name="devise",
        ),
        migrations.RemoveField(
            model_name="ligne",
            name="montant_devise",
        ),
        migrations.AlterField(
            model_name="justificatif",
            name="lien",
            field=models.URLField(
                blank=True, help_text="Document consultable en ligne.", max_length=500
            ),
        ),
    ]
