# Generated by Django 5.2.17 on 2026-10-02 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("compta", "0022_mono_devise"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mouvement",
            name="piece",
        ),
    ]
