# Generated by Django 5.2.17 on 2026-10-02 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compta", "0023_sans_piece"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportReleve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fichier", models.CharField(max_length=200)),
                (
                    "importe_le",
                    models.DateTimeField(auto_now_add=True, verbose_name="importé le"),
                ),
                (
                    "ajoutees",
                    models.PositiveIntegerField(
                        default=0, verbose_name="lignes ajoutées"
                    ),
                ),
                (
                    "doublons",
                    models.PositiveIntegerField(
                        default=0, verbose_name="doublons ignorés"
                    ),
                ),
                ("auteur", models.CharField(blank=True, max_length=100)),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="imports_releve",
                        to="compta.journal",
                    ),
                ),
            ],
            options={
                "verbose_name": "import de relevé",
                "verbose_name_plural": "imports de relevés",
                "ordering": ["-importe_le", "-pk"],
            },
        ),
    ]
