# Generated by Django 5.2.17 on 2026-10-02 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compta", "0027_lignereleve_ecartee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ligne",
            name="anal2",
            field=models.ForeignKey(
                blank=True,
                help_text="Comptes de classe 6 et 7 seulement.",
                limit_choices_to={"axe": 2},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lignes",
                to="compta.codeanalytique",
                verbose_name="axe 2",
            ),
        ),
    ]
