# Generated by Django 5.2.17 on 2026-10-05 04:22

from django.db import migrations, models


def corriger_axes(apps, schema_editor):
    """Axe 2 : jamais un code d'axe 1, jamais sur un compte de bilan (corrige les écritures existantes)."""
    Ligne = apps.get_model("compta", "Ligne")
    Ligne.objects.filter(anal2__isnull=False).exclude(anal2__axe=2).update(anal2=None)
    Ligne.objects.filter(anal2__isnull=False).exclude(compte__numero__startswith="6").exclude(compte__numero__startswith="7").update(anal2=None)


class Migration(migrations.Migration):

    dependencies = [
        ("compta", "0029_tiersprovisoire_coordonnees"),
    ]

    operations = [
        migrations.AddField(
            model_name="compte",
            name="projet",
            field=models.BooleanField(
                default=False,
                help_text="Charges et produits d'un projet (activité ponctuelle, opération durable) : toute écriture porte un code axe 2. Sinon : frais de fonctionnement (ex. 600000 / 600001).",
                verbose_name="compte de projet",
            ),
        ),
        migrations.RunPython(corriger_axes, migrations.RunPython.noop),
    ]
