# Generated by Django 6.1.1 on 2026-10-06 12:39

import django.db.models.deletion
from django.db import migrations, models


def budgets_axe2(apps, schema_editor):
    apps.get_model("compta", "Budget").objects.filter(anal2__isnull=False).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("compta", "0030_compte_projet"),
    ]

    operations = [
        migrations.RunPython(budgets_axe2, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name="budget",
            name="budget_une_cible",
        ),
        migrations.RemoveField(model_name="budget", name="anal2"),
        migrations.RemoveField(model_name="fiche", name="anal2"),
        migrations.RemoveField(model_name="ligne", name="anal2"),
        migrations.RemoveField(model_name="lignefiche", name="anal2"),
    ]
